import { AUTH } from '../core/auth.js';
import { showPage } from '../core/router.js';
import { S } from '../core/state.js';
import { AV, BADGE, BTN, ES, EVPILL, G, SCRD, esc, fmt, mon, sM, setA } from '../core/utils.js';
import { printFinanceReport } from '../engines/finances.js';
import { viewMember } from '../engines/members.js';
import { exportAll, exportAllCSV } from '../engines/settings.js';

export function pgDash(c){
  var m=S.data.members,v=S.data.visitors,f=S.data.finances,ev=S.data.events;
  var rev=f.filter(function(x){return x.type!=='depense';}).reduce(function(a,b){return a+(+b.montant||0);},0);
  var dep=f.filter(function(x){return x.type==='depense';}).reduce(function(a,b){return a+(+b.montant||0);},0);
  var now=new Date();
  var mRev=f.filter(function(x){return x.type!=='depense'&&sM(x.date,now);}).reduce(function(a,b){return a+(+b.montant||0);},0);
  var up=ev.filter(function(x){return new Date(x.date)>=now;}).sort(function(a,b){return new Date(a.date)-new Date(b.date);}).slice(0,3);
  var rec=m.slice().sort(function(a,b){return(b.createdAt||0)-(a.createdAt||0);}).slice(0,5);
  var pr=S.data.presences,lp=pr.length?pr[pr.length-1]:null;
  var bars=[],bL=[];
  for(var i=5;i>=0;i--){var d2=new Date();d2.setMonth(d2.getMonth()-i);var r2=f.filter(function(x){return x.type!=='depense'&&sM(x.date,d2);}).reduce(function(a,b){return a+(+b.montant||0);},0);var dp=f.filter(function(x){return x.type==='depense'&&sM(x.date,d2);}).reduce(function(a,b){return a+(+b.montant||0);},0);bars.push({r:r2,dp:dp});bL.push(d2.toLocaleString('fr',{month:'short'}));}
  var maxB=Math.max.apply(null,bars.map(function(b){return Math.max(b.r,b.dp);}));maxB=maxB||1;
  var svgB=bars.map(function(b,i){var x=18+i*62,rh=Math.round(b.r/maxB*68),dh=Math.round(b.dp/maxB*68);return '<rect x="'+x+'" y="'+(95-rh)+'" width="25" height="'+rh+'" fill="#2e7d32" rx="3" class="barGrow" style="animation-delay:'+(i*60)+'ms"><title>'+bL[i]+' — Revenus: '+mon(b.r)+'</title></rect><rect x="'+(x+27)+'" y="'+(95-dh)+'" width="25" height="'+dh+'" fill="#e53935" rx="3" class="barGrow" style="animation-delay:'+(i*60+40)+'ms"><title>'+bL[i]+' — Dépenses: '+mon(b.dp)+'</title></rect><text x="'+(x+26)+'" y="110" text-anchor="middle" font-size="9" fill="#9ba3b4">'+bL[i]+'</text>';}).join('');
  var sc={};m.forEach(function(mb){sc[mb.statut]=(sc[mb.statut]||0)+1;});
  var dc={pasteur:'#c9a84c',leader:'#0f2744',membre:'#1565c0',visiteur:'#9ba3b4'};
  var ci=2*Math.PI*40,off=0;
  var donut=Object.keys(sc).map(function(s2){var n=sc[s2],p=n/(m.length||1),d3=p*ci;var seg='<circle cx="48" cy="48" r="40" fill="none" stroke="'+(dc[s2]||'#ccc')+'" stroke-width="14" stroke-dasharray="'+d3+' '+(ci-d3)+'" stroke-dashoffset="'+(-off*ci)+'" transform="rotate(-90 48 48)" class="donutSeg"><title>'+s2+': '+n+' ('+Math.round(p*100)+'%)</title></circle>';off+=p;return seg;}).join('');
  var upH=up.length?up.map(EVPILL).join(''):ES('&#128197;','Aucun evenement');
  var recH=rec.map(function(mb){return '<div style="display:flex;align-items:center;gap:9px;padding:7px 0;border-bottom:1px solid var(--g2)">'+AV(mb.nom)+'<div style="flex:1"><div style="font-size:.84rem;font-weight:600">'+esc(mb.nom)+' '+esc(mb.prenom||'')+'</div><div style="font-size:.7rem;color:var(--g3)">'+esc(mb.statut||'')+'</div></div><button class="ai" onclick="viewMember(\''+mb.id+'\')">&#128065;</button></div>';}).join('')||ES('&#128101;','Aucun membre');
  var anns=S.data.announcements.slice().reverse().slice(0,2);
  var annH=anns.length?'<div class="cd" style="margin-top:18px"><div class="ch"><span class="ct2">&#128226; Annonces</span>'+BTN('bo bsm',"showPage('communication')",'Toutes')+'</div>'+anns.map(function(a){return '<div class="anb"><div class="ant">&#128226; '+esc(a.titre)+'</div><div class="anc">'+esc(a.contenu.slice(0,120))+(a.contenu.length>120?'...':'')+'</div><div class="and">'+fmt(a.date)+'</div></div>';}).join('')+'</div>':'';
  var presH='';
  if(lp){presH='<div class="cd" style="margin-top:18px"><div class="ch"><span class="ct2">&#128221; Derniere presence</span>'+BTN('bo bsm',"showPage('presences')",'Voir')+'</div><div style="display:flex;gap:18px;flex-wrap:wrap"><div><div style="font-size:.7rem;color:var(--g3)">Evenement</div><div style="font-weight:600">'+esc(lp.eventName)+'</div></div><div><div style="font-size:.7rem;color:var(--g3)">Date</div><div style="font-weight:600">'+fmt(lp.date)+'</div></div><div><div style="font-size:.7rem;color:var(--g3)">Presents</div><div style="font-weight:600;color:var(--bl)">'+(lp.nombrePresents||0)+'</div></div>'+(lp.offrande?'<div><div style="font-size:.7rem;color:var(--g3)">Offrande</div><div style="font-weight:600;color:var(--gn)">'+mon(lp.offrande)+'</div></div>':'')+'</div></div>';}
  // ── Bannière de bienvenue + badges de reconnaissance (léger, basé sur les vraies données) ──
  var hh=new Date().getHours();
  var hgreet=hh<12?'☀️ Bonjour':hh<18?'👋 Bon après-midi':'🌙 Bonsoir';
  var heroName=(typeof AUTH!=='undefined'&&AUTH.user)?((AUTH.profile&&AUTH.profile.name)||AUTH.user.email||'').split(' ')[0].split('@')[0]:'';
  var heroHtml='<div class="wbnr"><div class="wbt">'+hgreet+(heroName?', '+heroName:'')+' !</div><div class="wbs">Voici un aperçu de la vie de votre église, '+new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})+'.</div></div>';
  var badges=[];
  var newMembersCount=m.filter(function(x){return x.dateEntree&&sM(x.dateEntree,now);}).length;
  if(newMembersCount>0)badges.push('⭐ '+newMembersCount+' nouveau'+(newMembersCount>1?'x':'')+' membre'+(newMembersCount>1?'s':'')+' ce mois');
  var maxPres=pr.length?Math.max.apply(null,pr.map(function(x){return x.nombrePresents||0;})):0;
  if(lp&&pr.length>1&&maxPres>0&&(lp.nombrePresents||0)===maxPres)badges.push('🏆 Nouveau record de présence !');
  if(rev-dep>=0&&f.length>0)badges.push('💪 Budget à l\'équilibre');
  var answeredPrayers=S.data.prieres.filter(function(p2){return p2.statut==='exaucee';}).length;
  if(answeredPrayers>0)badges.push('🙏 '+answeredPrayers+' prière'+(answeredPrayers>1?'s':'')+' exaucée'+(answeredPrayers>1?'s':''));
  var gbadgesHtml=badges.length?'<div class="gbadges">'+badges.map(function(b){return '<span class="gbdg">'+b+'</span>';}).join('')+'</div>':'';
  c.innerHTML=heroHtml+gbadgesHtml+'<div class="sg">'+SCRD('&#128101; Membres',m.length,v.length+' visiteurs','var(--nv)')+SCRD('&#128176; Ce mois',mon(mRev),'Total: '+mon(rev),'var(--gn2)')+SCRD('&#128197; Evenements',ev.length,up.length+' a venir','var(--gd)')+SCRD('&#9962; Ministeres',S.data.ministries.length,S.data.sermons.length+' sermons','var(--pp)')+SCRD('&#128188; Solde',mon(rev-dep),'Dep: '+mon(dep),rev-dep>=0?'var(--tl)':'var(--rd)')+SCRD('&#128591; Prieres',S.data.prieres.length,S.data.prieres.filter(function(p2){return p2.statut==='exaucee';}).length+' exaucees','var(--pp)')+'</div><div style="display:grid;grid-template-columns:2fr 1fr;gap:18px;margin-bottom:18px"><div class="cd"><div class="ch"><span class="ct2">&#128202; Revenus vs Depenses</span><span style="font-size:.72rem;color:var(--g3)"><span style="color:var(--gn)">&#9646;</span> Rev &nbsp;<span style="color:var(--rd)">&#9646;</span> Dep</span></div><svg viewBox="0 0 410 118" style="width:100%;height:auto">'+svgB+'</svg></div><div class="cd" style="display:flex;flex-direction:column;align-items:center"><div class="ct2" style="margin-bottom:10px;align-self:flex-start">Composition</div><svg viewBox="0 0 96 96" style="width:96px;height:96px"><circle cx="48" cy="48" r="40" fill="none" stroke="#e4e7ed" stroke-width="14"/>'+donut+'<text x="48" y="44" text-anchor="middle" font-size="13" font-weight="700" fill="#0f2744">'+m.length+'</text><text x="48" y="56" text-anchor="middle" font-size="8" fill="#9ba3b4">membres</text></svg><div style="margin-top:10px;width:100%">'+Object.keys(sc).map(function(s2){return '<div style="display:flex;align-items:center;gap:6px;margin-bottom:4px;font-size:.74rem"><span style="width:9px;height:9px;border-radius:50%;background:'+(dc[s2]||'#ccc')+';flex-shrink:0"></span><span style="flex:1;text-transform:capitalize">'+s2+'</span><strong>'+sc[s2]+'</strong></div>';}).join('')+'</div></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:18px"><div class="cd"><div class="ch"><span class="ct2">&#128197; A venir</span>'+BTN('bo bsm',"showPage('evenements')",'Tous')+'</div>'+upH+'</div><div class="cd"><div class="ch"><span class="ct2">&#128101; Membres recents</span>'+BTN('bo bsm',"showPage('membres')",'Tous')+'</div>'+recH+'</div></div>'+annH+presH;
}
// ── MEMBRES ──

export function pgRapports(c){
  setA(BTN('bo','printFinanceReport()','&#128424; Imprimer')+' '+BTN('bo bsm','exportAllCSV()','&#128196; CSV')+' '+BTN('bg','exportAll()','&#128228; Export JSON'));
  var m=S.data.members,v=S.data.visitors,f=S.data.finances,ev=S.data.events;
  var rev=f.filter(function(x){return x.type!=='depense';}).reduce(function(a,b){return a+(+b.montant||0);},0);
  var dep=f.filter(function(x){return x.type==='depense';}).reduce(function(a,b){return a+(+b.montant||0);},0);
  var gB=[],gL=[];
  for(var i=5;i>=0;i--){var d2=new Date();d2.setMonth(d2.getMonth()-i);gB.push(m.filter(function(mb){return mb.createdAt&&sM(new Date(mb.createdAt).toISOString().slice(0,10),d2);}).length);gL.push(d2.toLocaleString('fr',{month:'short'}));}
  var gMax=Math.max.apply(null,gB);gMax=gMax||1;
  var pts=gB.map(function(n,i){return (35+i*64)+','+(85-Math.round(n/gMax*65));}).join(' ');
  var tS={};f.forEach(function(t){tS[t.type]=(tS[t.type]||0)+(+t.montant||0);});
  var tMax=Math.max.apply(null,Object.keys(tS).map(function(k){return tS[k];}).concat([1]));
  var typBars=Object.keys(tS).map(function(t){var tot=tS[t],pct=Math.round(tot/tMax*100),bg=t==='depense'?'var(--rd)':t==='dime'?'var(--gd)':'var(--nv)';return '<div style="margin-bottom:9px"><div style="display:flex;justify-content:space-between;font-size:.81rem;margin-bottom:3px"><span style="text-transform:capitalize">'+t+'</span><span class="'+(t==='depense'?'ec':'ic')+'" style="font-weight:600">'+mon(tot)+'</span></div><div class="pb"><div class="pf" style="width:'+pct+'%;background:'+bg+'"></div></div></div>';}).join('')||'<div style="color:var(--g3)">Aucune donnee</div>';
  var resumeItems=[['Membres actifs',m.filter(function(x){return['membre','leader','pasteur'].indexOf(x.statut)>=0;}).length,'bbl'],['Baptises',m.filter(function(x){return x.baptise==='oui';}).length,'bod'],['Convertis',v.filter(function(x){return x.converti==='oui';}).length,'bgr'],['Mariages celebres',S.data.marriages.filter(function(x){return x.statut==='Celebre';}).length,'btl'],['Baptemes celebres',S.data.baptisms.filter(function(x){return x.statut==='Celebre';}).length,'bbl'],['Prieres exaucees',S.data.prieres.filter(function(p){return p.statut==='exaucee';}).length,'bgr'],['Total revenus',mon(rev),'bgr'],['Total depenses',mon(dep),'bdr']].map(function(item){return '<div style="display:flex;justify-content:space-between;align-items:center;padding:8px;background:var(--g1);border-radius:7px"><span style="font-size:.82rem">'+item[0]+'</span>'+BADGE(item[2],String(item[1]))+'</div>';}).join('');
  c.innerHTML='<div class="sg" style="margin-bottom:18px">'+SCRD('Membres',m.length,'','var(--bl)')+SCRD('Visiteurs',v.length,'','var(--rs)')+SCRD('Conversion',(v.length?Math.round(v.filter(function(x){return x.converti==='oui';}).length/v.length*100):0)+'%','','var(--gn2)')+SCRD('Evenements',ev.length,'','var(--ig)')+SCRD('Sermons',S.data.sermons.length,'','var(--pp)')+SCRD('Solde',mon(rev-dep),'',rev-dep>=0?'var(--tl)':'var(--rd)')+'</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:18px"><div class="cd"><div class="ct2" style="margin-bottom:12px">Croissance membres (6 mois)</div><svg viewBox="0 0 420 105" style="width:100%;height:auto">'+(gB.length>1?'<polyline points="'+pts+'" fill="none" stroke="var(--nv)" stroke-width="2.5" stroke-linejoin="round"/>':'')+gB.map(function(n,i){var cx=35+i*64,cy=85-Math.round(n/gMax*65);return '<circle cx="'+cx+'" cy="'+cy+'" r="5" fill="var(--gd)"/><text x="'+cx+'" y="'+(cy-9)+'" text-anchor="middle" font-size="10" fill="var(--nv)">'+n+'</text><text x="'+cx+'" y="102" text-anchor="middle" font-size="8.5" fill="#9ba3b4">'+gL[i]+'</text>';}).join('')+'</svg></div><div class="cd"><div class="ct2" style="margin-bottom:12px">Finances par type</div>'+typBars+'</div></div><div class="cd"><div class="ch"><span class="ct2">Resume complet</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px">'+resumeItems+'</div></div>';
}

// ── RECHERCHE ──

export function pgRecherche(c){
  var q=S.ui.gs,ql=q.toLowerCase(),res=[];
  if(q.length>=2){S.data.members.filter(function(m){return(m.nom+' '+(m.prenom||'')+' '+(m.telephone||'')).toLowerCase().indexOf(ql)>=0;}).forEach(function(m){res.push({ic:'&#128101;',tp:'Membre',lb:m.nom+' '+(m.prenom||''),sb:m.telephone||m.statut||'',fn:'viewMember(\''+m.id+'\')'});});S.data.visitors.filter(function(v){return v.nom.toLowerCase().indexOf(ql)>=0;}).forEach(function(v){res.push({ic:'&#128587;',tp:'Visiteur',lb:v.nom,sb:'Visite: '+fmt(v.dateVisite),fn:''});});S.data.events.filter(function(e2){return e2.nom.toLowerCase().indexOf(ql)>=0;}).forEach(function(e2){res.push({ic:'&#128197;',tp:'Evenement',lb:e2.nom,sb:fmt(e2.date)+(e2.lieu?' - '+e2.lieu:''),fn:'showPage(\'evenements\')'});});S.data.sermons.filter(function(s2){return s2.titre.toLowerCase().indexOf(ql)>=0;}).forEach(function(s2){res.push({ic:'&#128214;',tp:'Sermon',lb:s2.titre,sb:(s2.predicateur||'')+' - '+fmt(s2.date),fn:'showPage(\'sermons\')'});});S.data.finances.filter(function(f2){return(f2.description||f2.donateur||'').toLowerCase().indexOf(ql)>=0;}).forEach(function(f2){res.push({ic:'&#128176;',tp:'Finance',lb:f2.description||f2.type,sb:mon(f2.montant)+' - '+fmt(f2.date),fn:'showPage(\'finances\')'});});S.data.prieres.filter(function(p){return(p.nom+p.sujet).toLowerCase().indexOf(ql)>=0;}).forEach(function(p){res.push({ic:'&#128591;',tp:'Priere',lb:p.nom,sb:p.sujet.slice(0,60),fn:'showPage(\'priere\')'});});}
  var resH=res.length?res.map(function(r){return '<div onclick="'+r.fn+'" style="display:flex;align-items:center;gap:11px;padding:11px;border-radius:9px;background:var(--g1);margin-bottom:7px;cursor:'+(r.fn?'pointer':'default')+'" onmouseover="this.style.background=\'var(--g2)\'" onmouseout="this.style.background=\'var(--g1)\'"><span style="font-size:1.25rem">'+r.ic+'</span><div style="flex:1"><div style="font-weight:600;font-size:.85rem">'+esc(r.lb)+'</div><div style="font-size:.73rem;color:var(--g3)">'+esc(r.sb)+'</div></div>'+BADGE('bbl',r.tp)+'</div>';}).join(''):'';
  c.innerHTML='<div class="cd"><div class="ch"><span class="ct2">Recherche Globale</span></div><input type="text" placeholder="Membres, evenements, sermons, finances..." value="'+esc(q)+'" oninput="S.ui.gs=this.value;pgRecherche(G(\'ct\'))" style="font-size:.95rem;padding:12px 14px;border-radius:9px;margin-bottom:18px">'+(q.length<2?ES('&#128269;','Tapez au moins 2 caracteres'):res.length?'<div style="font-size:.79rem;color:var(--g3);margin-bottom:12px">'+res.length+' resultat(s) pour "'+esc(q)+'"</div>'+resH:ES('&#128532;','Aucun resultat pour "'+esc(q)+'"'))+'</div>';
}

// ── SYNC ──
