import { S, VER, persist, remove } from '../core/state.js';
import { AV, BADGE, BTN, G, TW, celebrate, closeModal, esc, fmt, gv, lg, notify, openModal, setA, td, uid } from '../core/utils.js';

export function pgMembres(c){
  setA(BTN('bg','openAddMember()','+ Ajouter membre'));
  var q=S.ui.ms.toLowerCase(),st=S.ui.mst;
  var list=S.data.members.filter(function(m){var ok=!q||(m.nom+' '+(m.prenom||'')+' '+(m.telephone||'')).toLowerCase().indexOf(q)>=0;return ok&&(st==='tous'||m.statut===st);});
  var bm={visiteur:'bgy',membre:'bbl',leader:'bod',pasteur:'bod'};
  var sOpts=['tous','visiteur','membre','leader','pasteur'].map(function(s2){return '<option value="'+s2+'"'+(st===s2?' selected':'')+'>'+(s2.charAt(0).toUpperCase()+s2.slice(1))+'</option>';}).join('');
  var rows=list.length?list.map(function(m){return '<tr><td><div style="display:flex;align-items:center;gap:8px">'+AV(m.nom)+'<div><div style="font-weight:600">'+esc(m.nom)+' '+esc(m.prenom||'')+'</div><div style="font-size:.7rem;color:var(--g3)">'+(m.age?m.age+' ans':'')+'</div></div></div></td><td>'+esc(m.telephone||'-')+'</td><td>'+BADGE(bm[m.statut]||'bgy',m.statut||'-')+'</td><td>'+esc(m.ministere||'-')+'</td><td>'+fmt(m.dateEntree)+'</td><td><button class="ai" onclick="viewMember(\''+m.id+'\')">&#128065;</button><button class="ai" onclick="openAddMember(\''+m.id+'\')">&#9999;</button><button class="ai" onclick="delMember(\''+m.id+'\')">&#128465;</button></td></tr>';}).join(''):'<tr><td colspan="6" style="text-align:center;color:var(--g3);padding:28px">Aucun membre</td></tr>';
  c.innerHTML='<div class="srb"><input placeholder="Rechercher..." value="'+esc(S.ui.ms)+'" oninput="S.ui.ms=this.value;pgMembres(G(\'ct\'))"><select onchange="S.ui.mst=this.value;pgMembres(G(\'ct\'))">'+sOpts+'</select></div><div class="cd"><div class="ch"><span class="ct2">'+list.length+' membre'+(list.length!==1?'s':'')+'</span></div>'+TW('<tr><th>Nom</th><th>Tel</th><th>Statut</th><th>Ministere</th><th>Entree</th><th></th></tr>',rows)+'</div>';
}

export function openAddMember(id){
  var m=id?S.data.members.find(function(x){return x.id===id;})||{}:{};
  var mins=S.data.ministries.map(function(x){return '<option'+(m.ministere===x.nom?' selected':'')+'>'+esc(x.nom)+'</option>';}).join('');
  var stats=['visiteur','membre','leader','pasteur'].map(function(s2){return '<option value="'+s2+'"'+(m.statut===s2?' selected':'')+'>'+s2+'</option>';}).join('');
  openModal('<div class="mtt">'+(id?'Modifier':'Nouveau')+' Membre</div><div class="fg"><div class="fi"><label>Nom *</label><input id="mn" value="'+esc(m.nom||'')+'"></div><div class="fi"><label>Prenom</label><input id="mp" value="'+esc(m.prenom||'')+'"></div><div class="fi"><label>Age</label><input id="ma" type="number" value="'+(m.age||'')+'"></div><div class="fi"><label>Sexe</label><select id="ms"><option value="">--</option><option value="M"'+(m.sexe==='M'?' selected':'')+'>Masculin</option><option value="F"'+(m.sexe==='F'?' selected':'')+'>Feminin</option></select></div><div class="fi"><label>Telephone</label><input id="mt" value="'+esc(m.telephone||'')+'"></div><div class="fi"><label>Email</label><input id="mem" type="email" value="'+esc(m.email||'')+'"></div><div class="fi"><label>Statut</label><select id="mst2">'+stats+'</select></div><div class="fi s2"><label>Adresse</label><input id="mad" value="'+esc(m.adresse||'')+'"></div><div class="fi"><label>Date entree</label><input id="mde" type="date" value="'+(m.dateEntree||'')+'"></div><div class="fi"><label>Ministere</label><select id="mmin"><option value="">Aucun</option>'+mins+'</select></div><div class="fi"><label>Baptise</label><select id="mb2"><option value="non"'+(m.baptise!=='oui'?' selected':'')+'>Non</option><option value="oui"'+(m.baptise==='oui'?' selected':'')+'>Oui</option></select></div><div class="fi"><label>Date bapteme</label><input id="mdb" type="date" value="'+(m.dateBapteme||'')+'"></div><div class="fi s2"><label>Historique spirituel</label><textarea id="mhi">'+esc(m.historique||'')+'</textarea></div></div><div class="ma">'+BTN('bo','closeModal()','Annuler')+BTN('bg','saveMember(\''+(id||'')+'\')',' Enregistrer')+'</div>');
}

export async function saveMember(id){var nom=gv('mn');if(!nom){notify('Nom requis','error');return;}var ex=id?S.data.members.find(function(x){return x.id===id;}):null;var isNew=!id;await persist('members',{id:id||uid(),nom:nom,prenom:gv('mp'),age:gv('ma'),sexe:gv('ms'),telephone:gv('mt'),email:gv('mem'),statut:gv('mst2'),adresse:gv('mad'),dateEntree:gv('mde'),ministere:gv('mmin'),baptise:gv('mb2'),dateBapteme:gv('mdb'),historique:gv('mhi'),createdAt:ex?ex.createdAt:Date.now()});lg(id?'MODIF':'AJOUT',nom);closeModal();if(isNew)celebrate('🎉 '+nom+' rejoint la famille MbeukChurch !');else notify('✏️ '+nom+' a été mis à jour.','success');pgMembres(G('ct'));}
export function viewMember(id){var m=S.data.members.find(function(x){return x.id===id;});if(!m)return;var rows=[['Nom',m.nom+' '+(m.prenom||'')],['Age',m.age?m.age+' ans':'-'],['Sexe',m.sexe==='M'?'Masculin':m.sexe==='F'?'Feminin':'-'],['Tel',m.telephone||'-'],['Statut',m.statut||'-'],['Ministere',m.ministere||'-'],['Adresse',m.adresse||'-'],['Entree',fmt(m.dateEntree)],['Baptise',m.baptise==='oui'?'Oui':'Non'],['Dt bapteme',fmt(m.dateBapteme)]].map(function(p){return '<div><div style="font-size:.7rem;color:var(--g3);margin-bottom:2px">'+p[0]+'</div><div style="font-weight:600">'+esc(String(p[1]))+'</div></div>';}).join('');openModal('<div class="mtt">Fiche Membre</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;font-size:.84rem">'+rows+'<div style="grid-column:span 2"><div style="font-size:.7rem;color:var(--g3);margin-bottom:4px">Historique</div><div style="background:var(--g1);border-radius:7px;padding:9px;font-size:.81rem">'+esc(m.historique||'Aucun historique')+'</div></div></div><div class="ma">'+BTN('bo','closeModal()','Fermer')+BTN('bo','printMember(\''+m.id+'\')',' Imprimer')+BTN('bg','openAddMember(\''+m.id+'\');closeModal()','Modifier')+'</div>');}
export async function delMember(id){var m=S.data.members.find(function(x){return x.id===id;});if(!m||!confirm('Supprimer '+m.nom+' ?'))return;await remove('members',id);lg('SUPPR',m.nom);notify('Membre supprime','success');pgMembres(G('ct'));}

// ── VISITEURS ──

export function printMember(id){var m=S.data.members.find(function(x){return x.id===id;});if(!m)return;var w=window.open('','_blank');w.document.write('<!DOCTYPE html><html><head><title>Fiche</title><style>body{font-family:Georgia,serif;max-width:580px;margin:36px auto;color:#0f2744}h1{color:#c9a84c;border-bottom:2px solid #c9a84c;padding-bottom:7px}table{width:100%;border-collapse:collapse;margin-top:14px}td{padding:8px;border:1px solid #ddd}td:first-child{background:#f8f4ec;font-weight:bold;width:38%}@media print{button{display:none}}</style></head><body><h1>MbeukChurch - Fiche Membre</h1><table><tr><td>Nom</td><td>'+esc(m.nom)+' '+esc(m.prenom||'')+'</td></tr><tr><td>Age</td><td>'+(m.age||'-')+(m.age?' ans':'')+'</td></tr><tr><td>Telephone</td><td>'+esc(m.telephone||'-')+'</td></tr><tr><td>Adresse</td><td>'+esc(m.adresse||'-')+'</td></tr><tr><td>Statut</td><td>'+esc(m.statut||'-')+'</td></tr><tr><td>Ministere</td><td>'+esc(m.ministere||'-')+'</td></tr><tr><td>Entree</td><td>'+fmt(m.dateEntree)+'</td></tr><tr><td>Baptise</td><td>'+(m.baptise==='oui'?'Oui':'Non')+'</td></tr><tr><td>Historique</td><td>'+esc(m.historique||'-')+'</td></tr></table><p style="margin-top:18px;font-size:.78em;color:#999;text-align:center">Imprime le '+new Date().toLocaleDateString('fr-FR')+' - MbeukChurch v'+VER+'</p><div style="text-align:center;margin-top:14px"><button onclick="window.print()">Imprimer</button></div></body></html>');w.document.close();}
export function pgVisiteurs(c){
  setA(BTN('bg','openAddVisitor()','+ Nouveau visiteur'));
  var list=S.data.visitors;
  var rows=list.length?list.slice().reverse().map(function(v){return '<tr><td><strong>'+esc(v.nom)+'</strong></td><td>'+esc(v.telephone||'-')+'</td><td>'+fmt(v.dateVisite)+'</td><td>'+BADGE(v.converti==='oui'?'bgr':'bgy',v.converti==='oui'?'Converti':'En suivi')+'</td><td style="max-width:140px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(v.suivi||'-')+'</td><td>'+(v.converti!=='oui'?'<button class="ai" onclick="convertirV(\''+v.id+'\')" title="Convertir">&#9989;</button>':'')+'<button class="ai" onclick="openAddVisitor(\''+v.id+'\')">&#9999;</button><button class="ai" onclick="delVisitor(\''+v.id+'\')">&#128465;</button></td></tr>';}).join(''):'<tr><td colspan="6" style="text-align:center;color:var(--g3);padding:28px">Aucun visiteur</td></tr>';
  c.innerHTML='<div class="cd"><div class="ch"><span class="ct2">Visiteurs ('+list.length+')</span></div>'+TW('<tr><th>Nom</th><th>Tel</th><th>Date visite</th><th>Statut</th><th>Notes</th><th></th></tr>',rows)+'</div>';
}

export function openAddVisitor(id){var v=id?S.data.visitors.find(function(x){return x.id===id;})||{}:{};openModal('<div class="mtt">'+(id?'Modifier':'Nouveau')+' Visiteur</div><div class="fg"><div class="fi"><label>Nom *</label><input id="vn" value="'+esc(v.nom||'')+'"></div><div class="fi"><label>Telephone</label><input id="vt" value="'+esc(v.telephone||'')+'"></div><div class="fi"><label>Date visite</label><input id="vd" type="date" value="'+(v.dateVisite||td())+'"></div><div class="fi"><label>Via</label><select id="vs"><option>Bouche a oreille</option><option>Famille</option><option>Reseaux sociaux</option><option>Autre</option></select></div><div class="fi s2"><label>Notes</label><textarea id="vsu">'+esc(v.suivi||'')+'</textarea></div></div><div class="ma">'+BTN('bo','closeModal()','Annuler')+BTN('bg','saveVisitor(\''+(id||'')+'\')',' Enregistrer')+'</div>');}
export async function saveVisitor(id){var nom=gv('vn');if(!nom){notify('Nom requis','error');return;}var ex=id?S.data.visitors.find(function(x){return x.id===id;}):null;await persist('visitors',{id:id||uid(),nom:nom,telephone:gv('vt'),dateVisite:gv('vd'),source:gv('vs'),suivi:gv('vsu'),converti:ex?ex.converti:'non',createdAt:Date.now()});closeModal();notify('👋 '+nom+' a été enregistré(e) comme visiteur.','success');pgVisiteurs(G('ct'));}
export async function delVisitor(id){if(!confirm('Supprimer ?'))return;await remove('visitors',id);pgVisiteurs(G('ct'));}
export async function convertirV(id){var v=S.data.visitors.find(function(x){return x.id===id;});if(!v||!confirm('Convertir '+v.nom+' en membre ?'))return;v.converti='oui';await persist('visitors',v);await persist('members',{id:uid(),nom:v.nom,telephone:v.telephone,statut:'membre',dateEntree:td(),createdAt:Date.now()});lg('CONVERSION',v.nom);celebrate('🎉 '+v.nom+' est officiellement membre ! Bienvenue dans la famille.');pgVisiteurs(G('ct'));}

// ── FINANCES ──
